'use client';

import { useState, useEffect } from 'react';
import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Skeleton } from '@/components/ui/skeleton';
import { EmptyState } from '@/components/ui/empty-state';
import { cn } from '@/lib/utils';

interface Project {
  id: string;
  title: string;
  topic?: string;
  language: string;
  status: string;
  updatedAt: string;
  speakers: Array<{ speaker: { name: string } }>;
  _count: { turns: number; clips: number };
  /** Episode thumbnail (generated by the audio pipeline) */
  thumbnailUrl?: string | null;
}

const STATUS_META: Record<string, { label: string; variant: 'default' | 'success' | 'warning' | 'secondary' | 'outline' }> = {
  DRAFT: { label: 'Draft', variant: 'secondary' },
  OUTLINED: { label: 'Outlined', variant: 'outline' },
  DIALOGUE_READY: { label: 'Dialogue ready', variant: 'outline' },
  AUDIO_READY: { label: 'Audio ready', variant: 'success' },
  EXPORTED: { label: 'Exported', variant: 'success' },
  GENERATING: { label: 'Generating', variant: 'warning' },
  FAILED: { label: 'Failed', variant: 'warning' },
};

function statusMeta(status: string) {
  return STATUS_META[status] ?? { label: status.replace(/_/g, ' '), variant: 'secondary' as const };
}

function ProjectThumbnail({ project, className }: { project: Project; className?: string }) {
  const [imgFailed, setImgFailed] = useState(false);
  const showImg = project.thumbnailUrl && !imgFailed;
  return (
    <div
      className={cn(
        'relative flex h-32 items-center justify-center overflow-hidden rounded-md border border-border bg-gradient-to-br from-primary/10 via-background to-accent/20',
        className
      )}
      aria-hidden="true"
    >
      {showImg ? (
        // eslint-disable-next-line @next/next/no-img-element
        <img
          src={project.thumbnailUrl!}
          alt=""
          className="h-full w-full object-cover"
          onError={() => setImgFailed(true)}
          loading="lazy"
        />
      ) : (
        <span className="text-3xl">🎙️</span>
      )}
      <span className="absolute bottom-1.5 right-1.5 rounded-full bg-black/50 px-2 py-0.5 text-[10px] font-medium text-white backdrop-blur">
        {project.language.toUpperCase()}
      </span>
    </div>
  );
}

export default function ProjectsPage() {
  const [projects, setProjects] = useState<Project[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    fetch('/api/projects')
      .then((r) => {
        if (!r.ok) throw new Error(`HTTP ${r.status}`);
        return r.json();
      })
      .then((data) => {
        if (!cancelled) setProjects(Array.isArray(data) ? data : []);
      })
      .catch((e) => {
        if (!cancelled) setError(e instanceof Error ? e.message : 'Failed to load projects');
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, []);

  if (loading) {
    return (
      <div className="space-y-6" aria-busy="true">
        <div className="flex items-center justify-between">
          <Skeleton className="h-8 w-40" />
          <Skeleton className="h-10 w-32" />
        </div>
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {Array.from({ length: 6 }).map((_, i) => (
            <Card key={i} className="overflow-hidden">
              <Skeleton className="h-32 w-full rounded-none" />
              <CardContent className="space-y-3 py-4">
                <Skeleton className="h-5 w-3/4" />
                <Skeleton className="h-4 w-1/2" />
              </CardContent>
            </Card>
          ))}
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div role="alert" className="rounded-lg border border-destructive/30 bg-destructive/10 p-6 text-destructive">
        ⚠️ {error}
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold tracking-tight">Projects</h1>
          <p className="mt-1 text-sm text-muted-foreground">Your podcast episodes</p>
        </div>
        <Button asChild>
          <Link href="/projects/new">＋ New Podcast</Link>
        </Button>
      </div>

      {projects.length === 0 ? (
        <EmptyState
          icon="🎙️"
          title="No projects yet"
          description="Create your first Khmer-first AI podcast — outline, dialogue, audio, and export in minutes."
          actionLabel="Create Your First Podcast"
          actionHref="/projects/new"
        />
      ) : (
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {projects.map((p) => {
            const meta = statusMeta(p.status);
            return (
              <Link key={p.id} href={`/projects/${p.id}`} className="group focus-visible:outline-none">
                <Card className="card-lift h-full overflow-hidden">
                  <ProjectThumbnail project={p} />
                  <CardContent className="space-y-3 py-4">
                    <div>
                      <h3 className="font-semibold leading-tight group-hover:text-primary transition-colors">
                        {p.title}
                      </h3>
                      <p className="mt-0.5 line-clamp-1 text-sm text-muted-foreground">
                        {p.topic || 'No topic'}
                      </p>
                    </div>
                    <div className="flex flex-wrap gap-1.5">
                      <Badge variant={meta.variant} dot>
                        <span aria-hidden="true">{meta.variant === 'success' ? '✓' : meta.variant === 'warning' ? '◐' : '•'}</span>
                        <span>{meta.label}</span>
                      </Badge>
                      {p._count.turns > 0 && (
                        <Badge variant="secondary">{p._count.turns} turns</Badge>
                      )}
                      {p._count.clips > 0 && (
                        <Badge variant="outline">{p._count.clips} clips</Badge>
                      )}
                    </div>
                    <div className="flex items-center justify-between text-xs text-muted-foreground">
                      <span className="truncate">
                        {p.speakers.map((s) => s.speaker.name).join(', ') || 'No speakers'}
                      </span>
                      <span className="shrink-0 tabular-nums">
                        {new Date(p.updatedAt).toLocaleDateString()}
                      </span>
                    </div>
                  </CardContent>
                </Card>
              </Link>
            );
          })}
        </div>
      )}
    </div>
  );
}
